<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\ItemsPage.xaml.cs" />
    <Compile Remove="Views\LotteryInstagramFollowers.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Views\ItemsPage.xaml" />
    <EmbeddedResource Remove="Views\LotteryInstagramFollowers.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Html\ImageText.html" />
    <None Remove="Resources\Html\OflinePage.html" />
    <None Remove="Views\000" />
    <None Remove="Views\Views.rar" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Html\ImageText.html" />
    <EmbeddedResource Include="Resources\Html\OflinePage.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InstaSharper-latest" Version="1.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.28" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="6.0.8" />
    <PackageReference Include="Plugin.Permissions" Version="6.0.1" />
    <PackageReference Include="Plugin.Toast" Version="2.2.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2337" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Xamarin.Essentials">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Microsoft\Xamarin\NuGet\xamarin.essentials\1.6.1\lib\monoandroid10.0\Xamarin.Essentials.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\frmWinner.xaml.cs">
      <DependentUpon>frmWinner.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popups\HtmlModalPage.xaml.cs">
      <DependentUpon>HtmlModalPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\ActivityMain.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ContactList.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\frmSettings.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LotteryPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Popups\ActivityIndicatorLoading.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\_LoadingPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>